[package]
name = "daf-cache"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
daf-core = { path = "../daf-core" }
async-trait.workspace = true
tokio.workspace = true
thiserror.workspace = true
lru.workspace = true
serde.workspace = true
serde_json.workspace = true
moka = { version = "0.12", features = ["future"] }
tracing = "0.1"

[features]
redis = ["dep:redis"]
sled = ["dep:sled"]

[dependencies.redis]
version = "0.27"
optional = true
default-features = false
features = ["tokio-comp", "connection-manager"]

[dependencies.sled]
version = "0.34"
optional = true
